"""Compile a validated WorkflowDoc into a native Workflow tool script (JavaScript).

The emitted script is exactly what the Workflow tool expects: an `export const
meta = {...}` literal followed by a body that calls agent()/parallel()/pipeline().
workflow-glue never executes anything itself -- the skill hands this string (via a
file) to the native Workflow tool, which runs it.

Mapping (see the skill / plan for the authoring format):
  - doc                      -> meta + body
  - schemas.NAME             -> `const schema_NAME = {...};`  passed as agent {schema}
  - agent step, no fan-out   -> `const VAR = await agent(...)`
  - agent step, for_each     -> `const VAR = await parallel(OVER.map((item) => () => agent(...)))`
  - pipeline step            -> `const VAR = await pipeline(OVER, stageFn, ...)`
      each stage callback is `(prev, AS, i) => agent(...)`; a stage with fan_out
      wraps its body in a nested `parallel(...)` (the canonical Workflow pattern).
  - output                   -> `return EXPR;`  (default: object of all step results)
"""

from __future__ import annotations

import json
import re

from .errors import WorkflowError
from .expr import Scope, compile_expr, compile_single, compile_template
from .model import WorkflowDoc, Step, Stage

_GENERATED_HEADER = (
    "// GENERATED by workflow-glue from a .workflow.yaml -- do not edit by hand.\n"
    "// Re-generate with: workflow-glue compile <file>.workflow.yaml\n"
)

PREV_VAR = "prev"  # name of the first param of every pipeline stage callback


def _var(step_id: str) -> str:
    return "step_" + re.sub(r"[^A-Za-z0-9_]", "_", step_id)


def _phase_table(doc: WorkflowDoc):
    """Return (ordered [(id, title)], {id: title}) merging declared + inferred phases."""
    ordered = []
    by_id = {}
    for p in doc.phases:
        if p.id not in by_id:
            by_id[p.id] = p.title
            ordered.append((p.id, p.title))

    def add(pid):
        if pid and pid not in by_id:
            by_id[pid] = pid
            ordered.append((pid, pid))

    for step in doc.steps:
        add(step.phase)
        if step.is_pipeline:
            for stage in step.pipeline.stages:
                add(stage.phase)
    return ordered, by_id


def _agent_call(agent, phase_id, scope: Scope, phase_titles: dict) -> str:
    prompt_js = compile_template(agent.prompt, scope)
    opts = []
    if agent.schema:
        opts.append(f"schema: schema_{agent.schema}")
    if phase_id:
        opts.append(f"phase: {json.dumps(phase_titles[phase_id])}")
    if agent.model:
        opts.append(f"model: {json.dumps(agent.model)}")
    if agent.agentType:
        opts.append(f"agentType: {json.dumps(agent.agentType)}")
    if agent.isolation:
        opts.append(f"isolation: {json.dumps(agent.isolation)}")
    if agent.label:
        opts.append(f"label: {json.dumps(agent.label)}")
    if opts:
        return f"agent({prompt_js}, {{ {', '.join(opts)} }})"
    return f"agent({prompt_js})"


def _over_js(over, scope: Scope) -> str:
    if isinstance(over, list):
        return json.dumps(over)
    return compile_single(over, scope)


def _emit_flat_step(step: Step, defined: dict, phase_titles: dict) -> str:
    var = _var(step.id)
    if step.for_each is None:
        scope = Scope(step_vars=defined)
        call = _agent_call(step.agent, step.phase, scope, phase_titles)
        return f"const {var} = await {call};"
    # fan-out: parallel over a list, item bound to `item`
    over_js = _over_js(step.for_each, Scope(step_vars=defined))
    inner = Scope(step_vars=defined, locals={"item": "item"})
    call = _agent_call(step.agent, step.phase, inner, phase_titles)
    return f"const {var} = await parallel({over_js}.map((item) => () => {call}));"


def _emit_stage_callback(
    stage: Stage, as_name: str, prev_stage_id, defined: dict, phase_titles: dict
) -> str:
    prev = (prev_stage_id, PREV_VAR) if prev_stage_id else None
    if stage.fan_out is not None:
        fan = stage.fan_out
        over_scope = Scope(step_vars=defined, locals={as_name: as_name}, prev_stage=prev)
        over_js = _over_js(fan.over, over_scope)
        body_scope = Scope(
            step_vars=defined,
            locals={as_name: as_name, fan.as_: fan.as_},
            prev_stage=prev,
        )
        call = _agent_call(stage.agent, stage.phase, body_scope, phase_titles)
        body = f"parallel({over_js}.map(({fan.as_}) => () => {call}))"
    else:
        scope = Scope(step_vars=defined, locals={as_name: as_name}, prev_stage=prev)
        body = _agent_call(stage.agent, stage.phase, scope, phase_titles)
    return f"({PREV_VAR}, {as_name}, i) => {body}"


def _emit_pipeline_step(step: Step, defined: dict, phase_titles: dict) -> str:
    var = _var(step.id)
    pipe = step.pipeline
    over_js = _over_js(pipe.over, Scope(step_vars=defined))
    callbacks = []
    prev_id = None
    for stage in pipe.stages:
        callbacks.append(
            _emit_stage_callback(stage, pipe.as_, prev_id, defined, phase_titles)
        )
        prev_id = stage.id
    cb_block = ",\n  ".join(callbacks)
    return f"const {var} = await pipeline(\n  {over_js},\n  {cb_block},\n);"


def _emit_output(doc: WorkflowDoc, defined: dict) -> str:
    if doc.output:
        expr = compile_single(doc.output, Scope(step_vars=defined))
        return f"return {expr};"
    parts = ", ".join(f"{json.dumps(s.id)}: {_var(s.id)}" for s in doc.steps)
    return f"return {{ {parts} }};"


def compile_doc(doc: WorkflowDoc) -> str:
    """Compile a validated WorkflowDoc to a native Workflow tool JS script."""
    ordered_phases, phase_titles = _phase_table(doc)

    lines = [_GENERATED_HEADER]

    # meta
    meta_phases = ",\n    ".join(
        f"{{ title: {json.dumps(title)} }}" for _id, title in ordered_phases
    )
    meta = [
        "export const meta = {",
        f"  name: {json.dumps(doc.name)},",
        f"  description: {json.dumps(doc.description)},",
        f"  phases: [\n    {meta_phases}\n  ]," if ordered_phases else "  phases: [],",
        "};",
    ]
    lines.append("\n".join(meta))

    # inputs documentation (the engine exposes them as the `args` global)
    if doc.inputs:
        doc_lines = "\n".join(
            f"//   args.{name}: {spec.type}"
            + (f" -- {spec.description}" if spec.description else "")
            for name, spec in doc.inputs.items()
        )
        lines.append("// Inputs (provided via the Workflow `args` global):\n" + doc_lines)

    # schema consts
    if doc.schemas:
        schema_lines = []
        for name, body in doc.schemas.items():
            schema_lines.append(f"const schema_{name} = {json.dumps(body, indent=2)};")
        lines.append("\n".join(schema_lines))

    # body
    defined = {}
    body = []
    for step in doc.steps:
        if step.is_pipeline:
            body.append(_emit_pipeline_step(step, defined, phase_titles))
        else:
            body.append(_emit_flat_step(step, defined, phase_titles))
        defined[step.id] = _var(step.id)
    body.append(_emit_output(doc, defined))
    lines.append("\n".join(body))

    return "\n\n".join(lines) + "\n"
